name: wordle_turkish
description: Türkçe Wordle klonu

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/turkce_kelime_listesi.txt
    - assets/kelimeler.json